bookers/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'homes#top'
  resources :books

end

bookers/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookers/app/models/book.rb
class Book < ApplicationRecord

  validates :title, presence: true
  validates :body, presence: true

end

bookers/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

bookers/app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to book_path(@book.id)
    else
      render :new
    end

  end

  def edit
    @book = Book.find(params[:id])
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

bookers/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

end

bookers/app/helpers/application_helper.rb
module ApplicationHelper
end

bookers/app/helpers/books_helper.rb
module BooksHelper
end

bookers/app/helpers/homes_helper.rb
module HomesHelper
end

bookers/app/views/books/edit.html.erb
<h1>Editing Book</h1>
<!-- form_with部分 -->
<%= form_with model:@book, local: true do |f| %>

  <div class="field">
    <label for="book_title">Title</label>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <label for="book_body">Body</label>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit 'Update Book' %>
  </div>

<% end %>

  <a><%= book_to "Show", show_book_path(@book) %></a>
  <a> | </a>
  <a><%= book_to "Back", book_path(@book) %></a>

bookers/app/views/books/index.html.erb
<title>WebCampBackendNew</title>

<h1>Books</h1>
  <table>
      <thead>
        <tr>
          <th>Title</th>
          <th>Body</th>
          <th colspan="3"></th>
        </tr>
      </thead>
    <tbody>
        <tr>
          <% @books.each do |book| %>
            <td><%= book.title %></td>
            <td><%= book.body %></td>
            
            <td><%= book_to "Show", show_book_path(@book) %></td>
            <td><%= book_to "Edit", edit_book_path(@book) %></td>
            <td><%= book_to "Destroy", book_path(@book), method: :delete %></td> 
           
          <% end %>

bookers/app/views/books/new.html.erb
<title>WebCampBackendNew</title>

<h1>New book</h1>

<% if @book.errors.any? %>
  <%= @book.errors.count %> errors prohibited this book from being saved:
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<!-- form_with部分 -->
<%= form_with model: @book, url:'/books', local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Body</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book' %>
<% end %>

bookers/app/views/books/show.html.erb
<title>WebCampBackendNew</title>

<p><strong>Title:</strong></p>
<p><%= @book.title %></p>
<p><strong>Body:</strong></p>
<p><%= @book.body %></p>

<a><%= book_to "Edit", edit_book_path(@book) %></a>
<a> | </a>
<a><%= book_to "Back", book_path(@book) %></a>

bookers/app/views/homes/top.html.erb
<head>
  <title>WebCampBackendNew</title>
</head>

<body>
  <h1>ようこそ <strong>Bookers</strong>  へ！</h1>
  <p><strong>Bookers</strong>  では、さまざまな書籍に関するあなたの意見や</p><p>印象を共有し交換することができます</p>
  <p><a href="/books">start</a></p>


</body>

bookers/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>